spring:
  application:
    name: expense-management-server
  security:
    jwt:
      secret: ${JWT_SECRET}
      issuer: "expense-management"
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
