[versions]
kotlin = "2.2.21"
spring-boot = "4.0.0"
spring-dep-mgmt = "1.1.7"
kotlin-logging = "7.0.13"
archunit = "1.4.1"
mockito-kotlin = "5.4.0"
testcontainers = "1.21.3"


[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-spring = { id = "org.jetbrains.kotlin.plugin.spring", version.ref = "kotlin" }
kotlin-jpa = { id = "org.jetbrains.kotlin.plugin.jpa", version.ref = "kotlin" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dep-mgmt = { id = "io.spring.dependency-management", version.ref = "spring-dep-mgmt" }

[libraries]
spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-boot-starter-web = { module = "org.springframework.boot:spring-boot-starter-web" }
spring-boot-starter-security = { module = "org.springframework.boot:spring-boot-starter-security" }
jackson-module-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect" }

kotlin-logging = { module = "io.github.oshai:kotlin-logging", version.ref = "kotlin-logging" }
spring-boot-starter-validation = { module = "org.springframework.boot:spring-boot-starter-validation" }
spring-boot-docker-compose = { module = "org.springframework.boot:spring-boot-docker-compose" }
postgresql = { module = "org.postgresql:postgresql" }
flyway = { module = "org.springframework.boot:spring-boot-starter-flyway" }
flyway-postgresql = { module = "org.flywaydb:flyway-database-postgresql" }

junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher" }
spring-boot-starter-test = { module = "org.springframework.boot:spring-boot-starter-test" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5" }
archunit = { module = "com.tngtech.archunit:archunit", version.ref = "archunit" }
mockito-kotlin = { module = "org.mockito.kotlin:mockito-kotlin", version.ref = "mockito-kotlin" }
flyway-test = { module = "org.springframework.boot:spring-boot-starter-flyway-test" }
testcontainers-junit = { module = "org.testcontainers:junit-jupiter", version.ref = "testcontainers" }
testcontainers-postgresql = { module = "org.testcontainers:postgresql", version.ref = "testcontainers" }
